export const styles = {
  page: { minHeight: '100vh', background: 'var(--bg)' },
  content: { padding: '32px 24px', maxWidth: 1100, margin: '0 auto' },
  header: {
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'space-between',
    padding: '0 24px',
    height: 64,
    background: 'rgba(11,15,26,0.92)',
    backdropFilter: 'blur(12px)',
    borderBottom: '1px solid var(--border)',
    position: 'sticky',
    top: 0,
    zIndex: 100,
  },
  headerLeft: { display: 'flex', alignItems: 'center', gap: 16 },
  logo: { fontWeight: 700, fontSize: 16, letterSpacing: '-0.01em' },
  backBtn: {
    background: 'var(--bg3)',
    border: '1px solid var(--border)',
    color: 'var(--text2)',
    padding: '6px 14px',
    borderRadius: 8,
    fontSize: 13,
  },
  sessionPill: {
    display: 'flex',
    alignItems: 'center',
    gap: 8,
    background: 'rgba(79,142,247,0.1)',
    border: '1px solid rgba(79,142,247,0.25)',
    padding: '6px 14px',
    borderRadius: 20,
    fontSize: 13,
    color: 'var(--accent)',
  },
  liveDot: {
    width: 8,
    height: 8,
    borderRadius: '50%',
    background: 'var(--green)',
    boxShadow: '0 0 0 3px rgba(34,211,165,0.25)',
    animation: 'pulse 1.5s infinite',
  },
  card: { background: 'var(--card)', border: '1px solid var(--border)', borderRadius: 'var(--radius)', padding: 28, boxShadow: 'var(--shadow)' },
  cardTitle: { fontSize: 18, fontWeight: 700, marginBottom: 8, letterSpacing: '-0.01em' },
  cardSub: { color: 'var(--text2)', fontSize: 14, lineHeight: 1.6, marginBottom: 20 },
  divider: { height: 1, background: 'var(--border)', margin: '20px 0' },
  activeGrid: { display: 'grid', gridTemplateColumns: '340px 1fr', gap: 24, alignItems: 'start' },
  qrCard: { position: 'sticky', top: 88 },
  qrHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
  qrFrame: {
    background: '#fff',
    borderRadius: 12,
    padding: 12,
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    minHeight: 284,
    border: '1px solid var(--border)',
  },
  qrImg: { width: 260, height: 260, display: 'block' },
  qrPlaceholder: { display: 'flex', alignItems: 'center', justifyContent: 'center', height: 260 },
  qrHint: { fontSize: 12, color: 'var(--text3)', textAlign: 'center', margin: '12px 0' },
  infoGrid: { background: 'var(--bg3)', borderRadius: 10, padding: '4px 0', marginBottom: 16 },
  infoRow: { display: 'flex', justifyContent: 'space-between', alignItems: 'center', padding: '9px 14px', borderBottom: '1px solid var(--border)' },
  infoLabel: { fontSize: 12, color: 'var(--text2)' },
  infoVal: { fontSize: 13, fontWeight: 600 },
  code: { fontFamily: 'JetBrains Mono, monospace', fontSize: 12, color: 'var(--accent)', background: 'rgba(79,142,247,0.1)', padding: '2px 8px', borderRadius: 5 },
  attendCard: { minHeight: 400 },
  attendHeader: { display: 'flex', alignItems: 'center', justifyContent: 'space-between', marginBottom: 20 },
  countBadge: { background: 'rgba(34,211,165,0.12)', color: 'var(--green)', border: '1px solid rgba(34,211,165,0.25)', padding: '4px 12px', borderRadius: 20, fontSize: 13, fontWeight: 600 },
  emptyState: { textAlign: 'center', padding: '60px 20px' },
  emptyIcon: { fontSize: 40, marginBottom: 12, opacity: 0.4 },
  attendList: { listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 1 },
  attendItem: {
    display: 'flex',
    alignItems: 'center',
    gap: 14,
    padding: '14px 16px',
    background: 'var(--bg3)',
    borderRadius: 10,
    marginBottom: 6,
    borderLeft: '3px solid var(--green)',
    animation: 'fadeUp 0.3s ease',
  },
  avatar: {
    width: 40,
    height: 40,
    borderRadius: '50%',
    background: 'linear-gradient(135deg, var(--accent), var(--accent2))',
    display: 'flex',
    alignItems: 'center',
    justifyContent: 'center',
    fontSize: 16,
    fontWeight: 700,
    color: '#fff',
    flexShrink: 0,
  },
  studentInfo: { display: 'flex', flexDirection: 'column', flex: 1 },
  studentMeta: { display: 'flex', flexDirection: 'column', alignItems: 'flex-end', gap: 4 },
  distBadge: { background: 'rgba(34,211,165,0.12)', color: 'var(--green)', padding: '2px 8px', borderRadius: 6, fontSize: 12, fontWeight: 600 },
  timeBadge: { fontSize: 11, color: 'var(--text3)', fontFamily: 'JetBrains Mono, monospace' },
  finalList: { listStyle: 'none', display: 'flex', flexDirection: 'column', gap: 6 },
  finalItem: { display: 'flex', alignItems: 'center', gap: 12, padding: '10px 14px', background: 'var(--bg3)', borderRadius: 8 },
  finalNum: { width: 24, height: 24, borderRadius: '50%', background: 'var(--bg)', display: 'flex', alignItems: 'center', justifyContent: 'center', fontSize: 12, color: 'var(--text2)', border: '1px solid var(--border)' },
  toast: {
    position: 'fixed',
    bottom: 24,
    right: 24,
    background: 'var(--card)',
    border: '1px solid rgba(34,211,165,0.35)',
    borderLeft: '3px solid var(--green)',
    padding: '14px 18px',
    borderRadius: 12,
    display: 'flex',
    alignItems: 'center',
    gap: 12,
    boxShadow: '0 8px 32px rgba(0,0,0,0.5)',
    animation: 'slideIn 0.3s ease',
    zIndex: 999,
    minWidth: 260,
  },
  roleWrap: { minHeight: '100vh', display: 'flex', alignItems: 'center', justifyContent: 'center', padding: 24 },
  roleGrid: { display: 'flex', gap: 16, justifyContent: 'center', marginBottom: 32 },
  roleBtn: {
    background: 'var(--card)',
    border: '1px solid var(--border)',
    borderRadius: 16,
    padding: '28px 36px',
    cursor: 'pointer',
    textAlign: 'center',
    color: 'var(--text)',
    minWidth: 180,
    transition: 'all 0.2s',
    boxShadow: 'var(--shadow)',
  },
  roleBtnStudent: { borderColor: 'rgba(79,142,247,0.35)', background: 'rgba(79,142,247,0.05)' },
  roleBtnIcon: { fontSize: 40, display: 'block', marginBottom: 12 },
  featureRow: { display: 'flex', flexWrap: 'wrap', gap: 8, justifyContent: 'center' },
  featureChip: { background: 'var(--bg3)', border: '1px solid var(--border)', padding: '5px 14px', borderRadius: 20, fontSize: 13, color: 'var(--text2)' },
  centreCard: { width: '100%', maxWidth: 440, padding: 32, textAlign: 'center' },
  bigIcon: { fontSize: 52, marginBottom: 16 },
  videoWrap: {
    position: 'relative',
    background: '#000',
    borderRadius: 12,
    overflow: 'hidden',
    width: '100%',
    aspectRatio: '1',
    border: '2px solid var(--border)',
  },
  video: { width: '100%', height: '100%', objectFit: 'cover', display: 'block' },
  scanLine: {
    position: 'absolute',
    top: 0,
    left: 0,
    right: 0,
    height: 2,
    background: 'var(--accent)',
    boxShadow: '0 0 8px var(--accent)',
    animation: 'scanMove 2s linear infinite',
  },
  corner: { position: 'absolute', width: 28, height: 28, border: '3px solid var(--accent)' },
  tl: { top: 16, left: 16, borderRight: 'none', borderBottom: 'none' },
  tr: { top: 16, right: 16, borderLeft: 'none', borderBottom: 'none' },
  bl: { bottom: 16, left: 16, borderRight: 'none', borderTop: 'none' },
  br: { bottom: 16, right: 16, borderLeft: 'none', borderTop: 'none' },
};

export function injectAnimations() {
  const style = document.createElement('style');
  style.textContent = `
    @keyframes scanMove {
      0%   { top: 10%; }
      50%  { top: 88%; }
      100% { top: 10%; }
    }
    .role-btn:hover {
      border-color: var(--accent) !important;
      transform: translateY(-2px);
      box-shadow: 0 8px 32px rgba(79,142,247,0.15) !important;
    }
  `;
  document.head.appendChild(style);
}
